name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build Dockerfile and push image
      run: |
        IMAGE_NAME=test_container:${GITHUB_REF#refs/heads/}
        ls
        pwd
        docker-compose ps
